version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gabguard_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: gabguard
    restart: unless-stopped
    networks:
      - gabguard_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/gabguard --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  server:
    build:
      context: ./gabguard-server
    container_name: gabguard_server
    ports:
      - '443:8000'
    volumes:
      - ./gabguard-server:/app
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/gabguard'
      MONGO_DB_NAME: 'gabguard'
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYTHONUNBUFFERED: 1
      APP_PORT: 8000
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gabguard_network

  bot:
    build:
      context: ./gabguard-bot
      dockerfile: Dockerfile
    container_name: gabguard_bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_BASE_URL: https://server:8000
      TEMP_FILE_DIR: /app/temp
      ADMIN_USER_IDS: ${ADMIN_USER_IDS}
      TOXICITY_THRESHOLD_WARN: ${TOXICITY_THRESHOLD_WARN}
      TOXICITY_THRESHOLD_DELETE: ${TOXICITY_THRESHOLD_DELETE}
      ADMIN_NOTIFICATION_CHANNEL_ID: ${ADMIN_NOTIFICATION_CHANNEL_ID}
      COMMAND_PREFIX: ${COMMAND_PREFIX}
    volumes:
      - ./gabguard-bot:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - gabguard_network

volumes:
  mongodata:

networks:
  gabguard_network:
    driver: bridge
