version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gabguard_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: gabguard
    restart: unless-stopped

  server:
    build: ./gabguard-server
    container_name: gabguard_server
    ports:
      - '443:8000'
    volumes:
      - ./gabguard-server:/app
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/gabguard'
      MONGO_DB_NAME: 'gabguard'
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYTHONUNBUFFERED: 1
      APP_PORT: 8000
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodata:
